Update layout template
alphagov/govuk-design-guide pull request #76
Opened 2024-10-04 09:12 UTC by nnagewad

# Context
- This is a precurssor to the cookie banner PR.
- Decided to split PR into two, the first setting up the layout templates, and the second solely for the cookie banner and Analytics setup.

2024-10-04 11:38 UTC, joelanman requested changes

2024-10-04 11:38 UTC, joelanman commented on _includes/layouts/main.njk
> +{% endblock %}
```suggestion
{# Ready for custom blocks #}
```

2024-10-04 13:50 UTC, nnagewad commented on _includes/layouts/pattern-documentation.njk
>  {% block content %}
Good shout from @joelanman

2024-10-04 13:51 UTC, nnagewad commented on _includes/layouts/main.njk
> +{# Ready for custom blocks #}
Good shout from @joelanman

2024-10-07 12:47 UTC, calumryan approved these changes

2024-10-09 09:22 UTC, merged